<?php

namespace Plugins\ContentBundle\Repository;

use AppBundle\Repository\BaseRepository;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends BaseRepository
{
    /* @var $content \Plugins\ContentBundle\Entity\Content */
    public function getContentTextByKey($key, $strip_tags = false) {
        $content = $this->findOneByKey($key);
        if ($content == null) return null;
        return $strip_tags ? strip_tags($content->getContent()) : $content->getContent();
    }
}
