<?php

namespace Plugins\PracticAreaBundle\Repository;

use AppBundle\Repository\BaseRepository;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\LockMode;

/**
 * PracticAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PracticAreaRepository extends BaseRepository
{
    /**
     * Find short list of practic areas
		 *
     * @param string $phrases
     */
    public function findShortList() {
        $query = $this->createQueryBuilder('pa');
//         $query->where('pa.id > 0');
        $query->orderBy('pa.id', 'ASC');

        return $query->getQuery()->getResult();
    }
    public function findById($id){
      $query = $this->createQueryBuilder('pa');
      $query->where( 'pa.id = :identifier' )->setParameter('identifier',$id);

      return $query->getQuery()->getResult();
    }
    public function findByString($str){
      $query = $this->createQueryBuilder('pa');
      $query->where(
         $query->expr()->like('pa.name', ':str')
      )->setParameter('str','%'.$str.'%');

      return $query->getQuery()->getResult();
    }
}
