parameters:
#    kozei_service.example.class: Kozei\ServiceBundle\Example

services:
#    kozei_service.example:
#        class: %kozei_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
